(println '(and [(field "first-name" (eq "Adam")) (field "last-name" (eq "Mickiewicz"))]))

(defn get_info [x] {:value x :type (type x)})
(print (get_info true))
(print (get_info false))
(print (get_info nil))
(print (get_info 53))
(print (get_info 2.71))
(print (get_info \X))
(print (get_info "ABC"))
(print (get_info :abc))
(print (get_info 'abc))
(print (get_info '(:A :B :C)))
(print (get_info #{:A :B :C}))
(print (get_info {:name "Gumball"}))
(print (get_info [:A :B :C]))

(print [:A :B :C])
(print (map odd? [1 2 3 4 9 10]))
(print (filter odd? [1 2 3 4 9 10]))

(print ">>> " ''(+ 2 3))
(+ 53 (* 2 3))
